# Generated by Django 4.1.7 on 2023-03-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0002_course'),
        ('tutorme', '0002_course_alter_appuser_first_name_and_more'),
    ]

    operations = [
    ]
