# Generated by Django 4.1.3 on 2023-04-03 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0002_tutorprofile'),
        ('schedule_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='tutor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutorme.tutorprofile'),
        ),
    ]
